StartupEvents.registry('block', event => {
    event.create('ruined_controller')
    .displayName('Ruined Controller')
    .soundType('metal')
    .hardness(5)
    .resistance(5)
    .tagBlock('minecraft:mineable/pickaxe')
    .requiresTool(true),
    event.create('quartz_casing')
    .displayName('Quartz Casing')
    .soundType('stone')
    .hardness(5)
    .resistance(5)
    .tagBlock('minecraft:mineable/pickaxe')
    .requiresTool(false)
})