  StartupEvents.registry('fluid', e => {
    e.create('molten_netherite')
      .thickTexture(0x514240)
      .bucketColor(0x514240)
      .displayName('Molten Netherite')
      .luminosity(15)
      .viscosity(100)

    e.create('molten_zinc')
      .thickTexture(0x797C7F)
      .bucketColor(0x797C7F)
      .displayName('Molten Zinc')
      .luminosity(15)
      .viscosity(100)

    e.create('molten_ignitium')
      .thickTexture(0xF99401)
      .bucketColor(0xF99401)
      .displayName('Molten Ignitium')
      .luminosity(15)
      .viscosity(100)

    e.create('molten_witherite')
      .thickTexture(0x5C6575)
      .bucketColor(0x5C6575)
      .displayName('Molten Witherite')
      .luminosity(15)
      .viscosity(100)

    e.create('molten_scarlet_neodymium')
      .thickTexture(0xFC0029)
      .bucketColor(0xFC0029)
      .displayName('Molten Scarlet Neodymium')
      .luminosity(15)
      .viscosity(100)

    e.create('molten_azure_neodymium')
      .thickTexture(0x1936B9)
      .bucketColor(0x1936B9)
      .displayName('Molten Azure Neodymium')
      .luminosity(15)
      .viscosity(100)

     e.create('molten_cloggrum')
       .thickTexture(0xB89B7A)
       .bucketColor(0xB89B7A)
       .displayName('Molten Cloggrum')
       .luminosity(15)
       .viscosity(100)

     e.create('molten_arcanium')
       .thickTexture(0xF6C0FA)
       .bucketColor(0xF6C0FA)
       .displayName('Molten Arcanium')
       .luminosity(15)
       .viscosity(100)
    })
  