StartupEvents.registry('item', event => {
    event.create('polished_certus_quartz').displayName('Polished Certus Quartz')
    event.create('certus_quartz_sheet').displayName('Certus Quartz Sheet')
    event.create('polished_fluix').displayName('Polished Fluix')
    event.create('fluix_sheet').displayName('Fluix Sheet')
    event.create('silicon_sheet').displayName('Silicon Sheet')
    event.create('mushroom_paste').displayName('Mushroom Paste')
    event.create('mycelial_blend').displayName('Mycelial Blend')
    event.create('steel_ingot').displayName('Steel Ingot')
})