JEIEvents.hideItems(event => {
  event.hide([
    // '@ae2',
    // '@vintageimprovements',
    '@industrialforegoing',
    'apotheosis:sigil_of_socketing',
    'apotheosis:simple_reforging_table',
    'create_power_loader:andesite_chunk_loader',
    'create_power_loader:empty_andesite_chunk_loader',
    'create:refined_radiance_casing',
    'create:shadow_steel_casing',
    'createaddition:capacitor',
    'ends_delight:end_stone_knife',
    'ends_delight:purpur_knife',
    'irons_spellbooks:arcane_debris',
    'irons_spellbooks:arcane_salvage',
    'irons_spellbooks:blood_upgrade_orb',
    'irons_spellbooks:ender_upgrade_orb',
    'irons_spellbooks:evocation_upgrade_orb',
    'irons_spellbooks:fire_upgrade_orb',
    'irons_spellbooks:holy_upgrade_orb',
    'irons_spellbooks:ice_upgrade_orb',
    'irons_spellbooks:lightning_upgrade_orb',
    'irons_spellbooks:nature_upgrade_orb',
    'irons_spellbooks:upgrade_orb',
    'create_dd:kinetic_motor',
    'ae2:facade'
    ['storagedrawers:obsidian_storage_upgrade', 'storagedrawers:iron_storage_upgrade', 'storagedrawers:gold_storage_upgrade', 'storagedrawers:emerald_storage_upgrade', 'storagedrawers:upgrade_template'],
    // 'sophisticatedbackpacks:advanced_magnet_upgrade',
    // 'sophisticatedbackpacks:anvil_upgrade',
    // 'sophisticatedbackpacks:auto_blasting_upgrade',
    // 'sophisticatedbackpacks:auto_smoking_upgrade',
    // 'sophisticatedbackpacks:blasting_upgrade',
    // 'sophisticatedbackpacks:compacting_upgrade',
    // 'sophisticatedbackpacks:deposit_upgrade',
    // 'sophisticatedbackpacks:feeding_upgrade',
    // 'sophisticatedbackpacks:filter_upgrade',
    // 'sophisticatedbackpacks:magnet_upgrade',
    // 'sophisticatedbackpacks:pickup_upgrade',
    // 'sophisticatedbackpacks:pump_upgrade',
    // 'sophisticatedbackpacks:refill_upgrade',
    // 'sophisticatedbackpacks:restock_upgrade',
    // 'sophisticatedbackpacks:smelting_upgrade',
    // 'sophisticatedbackpacks:smoking_upgrade',
    // 'sophisticatedbackpacks:stack_upgrade_starter_tier',
    // 'sophisticatedbackpacks:stack_upgrade_tier_1',
    // 'sophisticatedbackpacks:stack_upgrade_tier_3',
    // 'sophisticatedbackpacks:stack_upgrade_tier_4',
    // 'sophisticatedbackpacks:tool_swapper_upgrade',
    // 'sophisticatedbackpacks:upgrade_base',
    // 'sophisticatedbackpacks:void_upgrade',
    'vintagedelight:cheese_burger',
    'vintagedelight:deluxe_burger',
    'vintageimprovements:concave_curving_head',
    'vintageimprovements:convex_curving_head',
    'vintageimprovements:curving_press',
    'vintageimprovements:spring_coiling_machine',
    'vintageimprovements:v_shaped_curving_head',
    'vintageimprovements:vacuum_chamber',
    'vintageimprovements:w_shaped_curving_head',
    '#vintageimprovements:springs',
    '#vintageimprovements:small_springs',
    '#vintagedelight:salt_lamp',
    ['createaddition:copper_spool', 'createaddition:gold_spool', 'createaddition:festive_spool'],
    'spelunkery:portal_fluid_bottle',
    'spelunkery:portal_fluid_bucket',
    'irons_spellbooks:iron_spell_book',
    'irons_spellbooks:copper_spell_book',
    ['everycomp:q/autumnity/orange_maple_hedge', 'everycomp:q/autumnity/orange_maple_leaf_carpet', 'everycomp:q/autumnity/red_maple_hedge', 'everycomp:q/autumnity/red_maple_leaf_carpet', 'regions_unexplored:maple_leaf_pile', 'regions_unexplored:red_maple_leaf_pile', 'regions_unexplored:orange_maple_leaf_pile', 'regions_unexplored:maple_sapling', 'regions_unexplored:orange_maple_sapling', 'everycomp:ap/regions_unexplored/maple_railing', 'everycomp:ap/regions_unexplored/maple_board_slab', 'everycomp:ap/regions_unexplored/maple_board_wall', 'everycomp:ap/regions_unexplored/maple_boards', 'everycomp:ap/regions_unexplored/maple_board_stairs', 'everycomp:c/regions_unexplored/maple_window', 'everycomp:c/regions_unexplored/maple_window_pane', 'everycomp:fd/regions_unexplored/maple_cabinet', 'everycomp:faf/regions_unexplored/maple_beehive', 'everycomp:q/regions_unexplored/maple_bookshelf', 'everycomp:q/regions_unexplored/maple_post', 'everycomp:q/regions_unexplored/stripped_maple_post', 'everycomp:q/regions_unexplored/vertical_maple_planks', 'everycomp:q/regions_unexplored/maple_ladder', 'everycomp:q/regions_unexplored/hollow_maple_log', 'everycomp:q/regions_unexplored/maple_chest', 'everycomp:q/regions_unexplored/maple_trapped_chest', 'everycomp:q/regions_unexplored/maple_hedge', 'everycomp:q/regions_unexplored/maple_leaf_carpet', 'everycomp:q/regions_unexplored/orange_maple_hedge', 'everycomp:q/regions_unexplored/orange_maple_leaf_carpet', 'everycomp:q/regions_unexplored/red_maple_hedge', 'everycomp:q/regions_unexplored/red_maple_leaf_carpet', 'everycomp:q/autumnity/maple_hedge', 'everycomp:q/autumnity/maple_leaf_carpet', 'everycomp:q/autumnity/yellow_maple_hedge', 'everycomp:q/autumnity/yellow_maple_leaf_carpet'],
    ['regions_unexplored:maple_trapdoor', 'regions_unexplored:maple_pressure_plate', 'regions_unexplored:maple_button', 'regions_unexplored:maple_sign', 'regions_unexplored:maple_hanging_sign', 'regions_unexplored:maple_boat', 'regions_unexplored:maple_chest_boat', 'regions_unexplored:red_maple_sapling', 'regions_unexplored:maple_shrub', 'regions_unexplored:orange_maple_shrub', 'regions_unexplored:red_maple_shrub', 'regions_unexplored:maple_leaves', 'regions_unexplored:orange_maple_leaves', 'regions_unexplored:red_maple_leaves', 'regions_unexplored:maple_branch', 'regions_unexplored:maple_log', 'regions_unexplored:maple_fence_gate', 'regions_unexplored:maple_door', 'regions_unexplored:maple_fence', 'regions_unexplored:maple_slab', 'regions_unexplored:maple_stairs', 'regions_unexplored:maple_planks', 'regions_unexplored:stripped_maple_wood', 'regions_unexplored:maple_wood', 'regions_unexplored:stripped_maple_log'],
    console.log('JEI items nuked!')
  ])
})

JEIEvents.addItems(event => {
  event.add([
  'vintageimprovements:belt_grinder',
  'vintageimprovements:grinder_belt',
  'minecraft:bundle',
  'industrialforegoing:fluid_extractor',
  console.log('JEI items added!')
  ])
})